# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        available_geometry = QtWidgets.QApplication.primaryScreen().availableGeometry()
        window_geometry = MainWindow.frameGeometry()
        window_geometry.moveCenter(available_geometry.center())
        MainWindow.move(window_geometry.topLeft())
        
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 551, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(64)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 190, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 190, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 190, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 190, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 280, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 350, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 400, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 450, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 500, 551, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.pushButton.clicked.connect(self.open_LR0_file)
        self.pushButton_2.clicked.connect(self.open_SLR_file)
        self.pushButton_3.clicked.connect(self.open_LR1_file)
        self.pushButton_4.clicked.connect(self.open_LALR_file)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bottom-Up Parsers"))
        self.pushButton.setText(_translate("MainWindow", "LR(0)"))
        self.pushButton_2.setText(_translate("MainWindow", "SLR"))
        self.pushButton_3.setText(_translate("MainWindow", "LR(1)"))
        self.pushButton_4.setText(_translate("MainWindow", "LALR"))
        self.label_2.setText(_translate("MainWindow", "Team D-18"))
        self.label_3.setText(_translate("MainWindow", "Jetty Sowmith                                BL.EN.U4AIE21060"))
        self.label_4.setText(_translate("MainWindow", "Kasa Anirudh                                BL.EN.U4AIE21066"))
        self.label_5.setText(_translate("MainWindow", "Lalith Abhiram Dasari                 BL.EN.U4AIE21071"))
        self.label_6.setText(_translate("MainWindow", "Mamidi Naveen Krishna              BL.EN.U4AIE21076"))
        
        
    def open_LR0_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./lr0  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)
                
    def open_SLR_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./SLR  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)
                
    def open_LR1_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./lr1  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)
                
    def open_LALR_file(self):
            # Close the current window
            MainWindow.close()

            # Start executing the other file
            FILE_PATH = "./LALR  main.py"
            try:
                subprocess.Popen([sys.executable, FILE_PATH])
            except Exception as e:
                print("Error executing file:", e)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
